-- ============================================================
-- SYNTHÈSE PAR CATÉGORIE (ex "AG" / "Analyse" fusionnées côté front)
-- ============================================================
-- La configuration des catégories (quelles sources/types/descriptions/
-- fournisseurs composent "Dons", "Frais vétérinaires", etc.) est stockée
-- dans config_compta (cle='ag_categories'), même mécanisme que
-- 'periodes'. Structure d'un élément :
--   {"cat":"Dons","sens":"recette","sources":["banque","caisse"],
--    "types":["Dons","Don libre"],"descriptions":[],"fournisseurs":[]}
--
-- ATTENTION vérifiée en reprenant l'ancien système : si une même
-- catégorie coche à la fois "banque" (ou "caisse") ET "cheques"/"remises"
-- comme sources, un chèque/une remise encaissé(e) est compté deux fois
-- (une fois comme chèque/remise, une fois comme mouvement bancaire une
-- fois encaissé). Par défaut, aucune catégorie ne mélange les deux — la
-- page ci-jointe avertit visuellement si on active cette combinaison.
--
-- NOTE : ce fichier ne contient plus que de la documentation. Il définissait
-- à l'origine une fonction dédiée enregistrer_ag_categories(), qui n'a en
-- fait jamais été utilisée par aucune page — analyse.html enregistre cette
-- config via la fonction générique definir_config_compta() (voir
-- 024_config_generique.sql), qui suffit. Fonction supprimée pour ne pas
-- garder du code mort ; rien à exécuter dans ce fichier.
--
-- Si vous l'aviez déjà exécutée par le passé, cette ligne la retire
-- proprement de la base (sans risque si elle n'existe pas) :
drop function if exists enregistrer_ag_categories(jsonb);
